name: E2E

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# schedule:
# Scheduled run: once for every work day
#    - cron: '0 0 * * 1-5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "e2e"
  e2e:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install a chrome driver
        uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: '94.0.4606.81'

      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test-ci

      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: reports
